### ISSUE TITLE
License Remake

### ISSUE THREAD

**Issue by HoldYourWaffle** [heyigor/FortApocalypse#1]
Would it be legal for me to make a remake of Fort Apocalypse called Fort Zapocalypse?

**Comment by heyigor** [comment]
@Ravian2002 no problem. Happy to explain. From this [link](http://creativecommons.org/licenses/by-nc-nd/2.5/)  we have:
- Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- NonCommercial — You may not use the material for commercial purposes.
- NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

So specifically to answer your question. No you can't make a derivative.

The goal is for you to learn from this code, make something new with your own code, your own art, your own ideas, but take pieces or parts of this, but not an exact copy of the game.

Hope that helps.

**Comment by Ravian2002** [comment]
So I can't copy the "story"/gameplay of the game?
(English is not my native language so it's a bit confusing)

**Comment by heyigor** [comment]
@Ravian2002 you can take elements of the story, but not use the name, Fort Apocalypse, or any variant of the name Fort Apocalypse.

**Comment by Ravian2002** [comment]
And still non-commercial (when I call it like "peanutbutter")?
(Just want to be absolutly sure)
