### ISSUE TITLE
how was it developed?

### ISSUE THREAD

**Issue by exebook** [heyigor/FortApocalypse#2]
Loved to play it long ago, and still replay sometimes. Thanks for the release.

If you have a moment, could you please kindly describe briefly what kind of tool set you used to program it? I mean what kind of an editor and assembler were involved, was it under Atari DOS? When you run it and it crashed did you have to restart the whole OS? What hardware you used to develop it? Did you save to floppy?

**Comment by heyigor** [comment]
Sure thing.

Development was done with Synapse Software in house assembler SynAssembler, that we released at some point. It ran on the Atari 800. All files were saved with Atari DOS to floppies. 

https://archive.org/details/a8b_SynAssembler_1982_Synapse_Software_US_req_OSb

A crash, usually mean a reboot, however, things were simpler then so it was fast. I used a debugging technique in which I changed a scan line color vertically to denote places in the code. That allows me to follow logic visually.

There was no serial output debugger, although that could have been written. The joysticks were a serial I/O port, and the Atari did have a slow serial output.

All development was done on a Atari 800, with 32k of RAM.
